const { BAD_REQUEST_STATUS } = 404;
const { SERVER_ERROR_STATUS } = 500;
const { VALIDATION_ERROR_STATUS } = 400;
const { CAST_ERROR_STATUS } = 400;

module.exports = {
  BAD_REQUEST_STATUS,
  SERVER_ERROR_STATUS,
  VALIDATION_ERROR_STATUS,
  CAST_ERROR_STATUS,
};
