const BAD_REQUEST_STATUS = 400;
const SERVER_ERROR_STATUS = 500;
const NOT_FOUND_STATUS = 404;
const SUCCESS_STATUS = 200;
const CREATED_STATUS = 201;
const EMAIL_EXISTS_STATUS = 409;
const INCORRECT_TOKEN_STATUS = 401;

module.exports = {
  BAD_REQUEST_STATUS,
  SERVER_ERROR_STATUS,
  NOT_FOUND_STATUS,
  CREATED_STATUS,
  SUCCESS_STATUS,
  EMAIL_EXISTS_STATUS,
  INCORRECT_TOKEN_STATUS,
};
